### ISSUE TITLE
Errors in building

### ISSUE THREAD

**Issue by persiaitc** [LostSoulFly/MiningService#1]
Hello
Did you build this version with Visual studio?
When i did, it turn me 20 Errors!
I'm not a professional programmer.
please help.
![ss](https://user-images.githubusercontent.com/35273513/35063812-704ab6a8-fbdd-11e7-9940-b7b99ec3eb21.JPG)

**Comment by LostSoulfly** [comment]
Which version of Visual Studio are you using? Also, I would refrain from compiling the current version as I'm working through some bugs that I've accidentally recently.

**Comment by persiaitc** [comment]
Thanks.
I'm using Visual Studio 2015.

**Comment by LostSoulfly** [comment]
I've probably used some coding practices that are not supported in VS 2015. I'll add that VS 2017 is required to compile.

**Comment by persiaitc** [comment]
Yes. You are right. thanks again
