### ISSUE TITLE
Running problem

### ISSUE THREAD

**Issue by persiaitc** [LostSoulFly/MiningService#2]
Dear LostSouFly
I tried your code. Every thing was ok and the mining service ran successfully but CPU remains 0 percent after starting the service! It seems there is a problem but i can't find it. Could you help me?
This is the running environment:

![image](https://user-images.githubusercontent.com/35273513/35288515-26adbc38-007a-11e8-84a2-561e1e34157d.png)

**Comment by LostSoulfly** [comment]
Try running it not as a service, just use the GUI editor and Run instead of
Start service. Also check the log. It may be an issue with your miner
configs.

**Comment by persiaitc** [comment]
Thanks. Logs were normal.

1/23/2018 10:06:40 PM (1620) LOG: Starting MiningService: 0.1.2
1/23/2018 10:06:40 PM (1620) LOG: Initializing MiningService.. CPU Cores: 8
1/23/2018 10:06:40 PM (1620) LOG: Battery found. IsBatteryFull: False
1/23/2018 10:06:40 PM (1620) LOG: MiningService Initialized. Is SYSTEM: True. User: SYSTEM
1/23/2018 10:06:42 PM (1620) LOG: Attempting to start IdleMon in SessionID 1
1/23/2018 10:06:42 PM (1620) LOG: MiningService is running
1/23/2018 10:06:42 PM (1620) LOG: idleMon user Alex connected.
1/23/2018 10:06:42 PM (3264): Logging initialized.
1/23/2018 10:06:42 PM (3264): IdleTime received from MiningService: 1
1/23/2018 10:06:42 PM (3264): Fullscreen monitoring initialized.
1/23/2018 10:06:42 PM (3264): Received IgnoreFullscreenApp: explorer
1/23/2018 10:06:42 PM (3264): Received IgnoreFullscreenApp: LockApp

**Comment by LostSoulfly** [comment]
Log doesn't show it started any miners, make sure they're setup and enabled
